In [1]:
# Pandas group by

In [2]:
import pandas as pd

In [3]:
flights= pd.read_csv("flights.csv")

In [4]:
flights.head()

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0
2,1,1,4,MQ,DFW,VPS,1305,36.0,85.0,641,1453,35.0,0,0
3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
4,1,1,4,WN,LAX,MCI,1720,48.0,166.0,1363,2225,39.0,0,0

In [5]:
# av delay- per airline

In [6]:
flights.groupby("AIRLINE")['ARR_DELAY'].mean()

AIRLINE
AA     5.542661
AS    -0.833333
B6     8.692593
DL     0.339691
EV     7.034580
F9    13.630651
HA     4.972973
MQ     6.860591
NK    18.436070
OO     7.593463
UA     7.765755
US     1.681105
VX     5.348884
WN     6.397353
Name: ARR_DELAY, dtype: float64

### Group by agg methods avaiable
1. min
2. max
3. median
4. sum
5. count
6. std
7. var
8. size
9. describe
10. nunique
11. idxmax
12. idxmin

###  Grouping and aggregating with multiple columns and functions

1. Find the number of cancelled flights for every airline per weekday

In [11]:
flights.head()

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0
2,1,1,4,MQ,DFW,VPS,1305,36.0,85.0,641,1453,35.0,0,0
3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
4,1,1,4,WN,LAX,MCI,1720,48.0,166.0,1363,2225,39.0,0,0

In [19]:
flights.groupby(["AIRLINE","WEEKDAY"])['CANCELLED'].sum()

AIRLINE  WEEKDAY
AA       1          41
         2           9
         3          16
         4          20
         5          18
         6          21
         7          29
AS       1           0
         2           0
         3           0
         4           0
         5           0
         6           0
         7           0
B6       1           0
         2           1
         3           0
         4           0
         5           0
         6           0
         7           0
DL       1          10
         2           8
         3           8
         4           3
         5           3
         6           4
         7           2
EV       1          30
         2          21
                    ..
OO       6          20
         7          29
UA       1          23
         2          20
         3           9
         4           9
         5          12
         6           6
         7          14
US       1           6
         2           4
         3           1
         4           1
         5           2
         6           1
         7           6
VX       1           1
         2           0
         3           0
         4           2
         5           1
         6           0
         7           2
WN       1          16
         2          25
         3          18
         4          10
         5           7
         6          10
         7           7
Name: CANCELLED, dtype: int64

Find the number and percentage of cancelled and diverted flights for every airline per weekday

In [22]:
flights.groupby(["AIRLINE","WEEKDAY"])['CANCELLED','DIVERTED'].agg(['sum','mean'])

                CANCELLED           DIVERTED
                      sum      mean      sum      mean
AIRLINE WEEKDAY
AA      1              41  0.032106        6  0.004699
        2               9  0.007341        2  0.001631
        3              16  0.011949        2  0.001494
        4              20  0.015004        5  0.003751
        5              18  0.014151        1  0.000786
        6              21  0.018667        9  0.008000
        7              29  0.021837        1  0.000753
AS      1               0  0.000000        0  0.000000
        2               0  0.000000        0  0.000000
        3               0  0.000000        0  0.000000
        4               0  0.000000        0  0.000000
        5               0  0.000000        0  0.000000
        6               0  0.000000        0  0.000000
        7               0  0.000000        0  0.000000
B6      1               0  0.000000        0  0.000000
        2               1  0.012658        0  0.000000
        3               0  0.000000        0  0.000000
        4               0  0.000000        0  0.000000
        5               0  0.000000        0  0.000000
        6               0  0.000000        1  0.016667
        7               0  0.000000        1  0.011364
DL      1              10  0.006068        2  0.001214
        2               8  0.005208        5  0.003255
        3               8  0.005131        4  0.002566
        4               3  0.001940        2  0.001294
        5               3  0.001982        3  0.001982
        6               4  0.003195        4  0.003195
        7               2  0.001294        4  0.002587
EV      1              30  0.034130        3  0.003413
        2              21  0.023918        3  0.003417
...                   ...       ...      ...       ...
OO      6              20  0.024125        2  0.002413
        7              29  0.031385        3  0.003247
UA      1              23  0.018914        4  0.003289
        2              20  0.017498        2  0.001750
        3               9  0.007799        2  0.001733
        4               9  0.007719        3  0.002573
        5              12  0.010195        2  0.001699
        6               6  0.006682        2  0.002227
        7              14  0.013487        4  0.003854
US      1               6  0.026906        0  0.000000
        2               4  0.018018        0  0.000000
        3               1  0.004545        0  0.000000
        4               1  0.003953        1  0.003953
        5               2  0.009050        0  0.000000
        6               1  0.004695        0  0.000000
        7               6  0.022814        0  0.000000
VX      1               1  0.007194        0  0.000000
        2               0  0.000000        0  0.000000
        3               0  0.000000        0  0.000000
        4               2  0.014184        0  0.000000
        5               1  0.006667        0  0.000000
        6               0  0.000000        0  0.000000
        7               2  0.014815        1  0.007407
WN      1              16  0.012708        3  0.002383
        2              25  0.019562        0  0.000000
        3              18  0.014118        2  0.001569
        4              10  0.007911        4  0.003165
        5               7  0.005828        0  0.000000
        6              10  0.010132        3  0.003040
        7               7  0.006066        3  0.002600

[98 rows x 4 columns]

For each origin and destination, find the total number of flights, the number and percentage of cancelled flights,the average and varaince of airtime

In [24]:
flights.head(2)

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0

In [26]:
flights.groupby(["ORG_AIR",'DEST_AIR'])['CANCELLED','AIR_TIME'].agg(['size','mean','var'])

                 CANCELLED                     AIR_TIME              \
                      size      mean       var     size        mean
ORG_AIR DEST_AIR
ATL     ABE             31  0.000000  0.000000       31   96.387097
        ABQ             16  0.000000  0.000000       16  170.500000
        ABY             19  0.000000  0.000000       19   28.578947
        ACY              6  0.000000  0.000000        6   91.333333
        AEX             40  0.000000  0.000000       40   78.725000
        AGS             83  0.000000  0.000000       83   28.819277
        ALB             33  0.000000  0.000000       33  108.181818
        ANC              2  0.000000  0.000000        2  438.500000
        ASE              1  0.000000       NaN        1  192.000000
        ATW             10  0.000000  0.000000       10  106.400000
        AUS            105  0.000000  0.000000      105  117.571429
        AVL             56  0.000000  0.000000       56   33.892857
        AVP             14  0.000000  0.000000       14   94.214286
        BDL             69  0.014493  0.014493       69  109.750000
        BHM             86  0.011628  0.011628       86   28.800000
        BMI             21  0.000000  0.000000       21   80.095238
        BNA            108  0.000000  0.000000      108   38.574074
        BOS            145  0.013793  0.013697      145  120.776224
        BQK             29  0.000000  0.000000       29   41.379310
        BTR             76  0.000000  0.000000       76   69.618421
        BTV             14  0.000000  0.000000       14  116.785714
        BUF             42  0.000000  0.000000       42   93.214286
        BWI            183  0.000000  0.000000      183   80.540984
        BZN              1  0.000000       NaN        1  219.000000
        CAE             73  0.000000  0.000000       73   33.397260
        CAK             56  0.000000  0.000000       56   72.964286
        CHA             75  0.013333  0.013333       75   24.121622
        CHO             28  0.000000  0.000000       28   66.928571
        CHS             93  0.000000  0.000000       93   42.935484
        CID             27  0.000000  0.000000       27   99.481481
...                    ...       ...       ...      ...         ...
SFO     MSP             72  0.013889  0.013889       72  189.380282
        MSY              5  0.000000  0.000000        5  209.000000
        OGG             49  0.000000  0.000000       49  299.877551
        OKC             10  0.000000  0.000000       10  162.300000
        ONT             71  0.014085  0.014085       71   60.042857
        ORD            213  0.009390  0.009345      213  216.207729
        OTH              8  0.250000  0.214286        8   69.166667
        PDX            100  0.000000  0.000000      100   78.830000
        PHL             62  0.032258  0.031729       62  287.633333
        PHX            132  0.015152  0.015036      132   91.176923
        PIT              5  0.000000  0.000000        5  256.200000
        PSC              6  0.166667  0.166667        6   78.800000
        PSP             66  0.015152  0.015152       66   63.230769
        RDD             23  0.086957  0.083004       23   37.809524
        RDM             20  0.050000  0.050000       20   67.842105
        RDU             17  0.000000  0.000000       17  275.588235
        RNO             53  0.000000  0.000000       53   34.056604
        SAN            200  0.040000  0.038593      200   69.046875
        SAT              6  0.000000  0.000000        6  172.166667
        SBA             66  0.015152  0.015152       66   47.615385
        SBP             28  0.000000  0.000000       28   42.321429
        SEA            208  0.009615  0.009569      208   96.495146
        SLC            113  0.008850  0.008850      113   81.339286
        SMF             59  0.033898  0.033314       59   21.052632
        SMX             14  0.071429  0.071429       14   40.846154
        SNA            122  0.032787  0.031974      122   64.059322
        STL             20  0.000000  0.000000       20  198.900000
        SUN             10  0.000000  0.000000       10   78.000000
        TUS             20  0.000000  0.000000       20  100.200000
        XNA              2  0.000000  0.000000        2  173.500000


                         var
ORG_AIR DEST_AIR
ATL     ABE        45.778495
        ABQ        87.866667
        ABY         6.590643
        ACY        11.466667
        AEX        47.332692
        AGS         9.393770
        ALB        41.903409
        ANC        40.500000
        ASE              NaN
        ATW        61.377778
        AUS       110.131868
        AVL        10.170130
        AVP        28.335165
        BDL        38.906716
        BHM        23.638095
        BMI       133.290476
        BNA         5.648667
        BOS        66.991825
        BQK        10.100985
        BTR        24.745789
        BTV        39.412088
        BUF        16.172474
        BWI        37.040894
        BZN              NaN
        CAE         6.187215
        CAK        28.398701
        CHA        19.669937
        CHO        25.253968
        CHS        71.234923
        CID        76.028490
...                      ...
SFO     MSP       130.953320
        MSY        93.000000
        OGG       163.193027
        OKC        92.011111
        ONT        12.505383
        ORD       101.602270
        OTH        33.366667
        PDX        30.283939
        PHL        95.795480
        PHX        29.387060
        PIT        76.200000
        PSC        19.700000
        PSP        17.586538
        RDD        28.861905
        RDM        36.584795
        RDU       110.507353
        RNO         4.900581
        SAN        17.667948
        SAT       116.566667
        SBA        32.459135
        SBP        29.189153
        SEA        42.992659
        SLC        23.379344
        SMF         8.729323
        SMX         3.641026
        SNA        11.338331
        STL       101.042105
        SUN        25.777778
        TUS        35.221053
        XNA         0.500000

[1130 rows x 6 columns]

In [27]:
# removing multiindex after group by

Find total and average mils flown, max and min arrival delay for each airline for each weekday

In [28]:
flights.head(1)

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0

In [32]:
d1= {'DIST':['count','mean'],'ARR_DELAY':['max','min']}

In [33]:
flights.groupby(['AIRLINE','WEEKDAY']).agg(d1)

                 DIST              ARR_DELAY
                count         mean       max   min
AIRLINE WEEKDAY
AA      1        1277  1139.691464     551.0 -60.0
        2        1226  1107.876020     725.0 -52.0
        3        1339  1117.748320     473.0 -45.0
        4        1333  1089.567892     349.0 -46.0
        5        1272  1122.444182     732.0 -41.0
        6        1125  1124.746667     858.0 -50.0
        7        1328  1100.832831     626.0 -49.0
AS      1         118  1029.474576     145.0 -28.0
        2         106  1081.896226      86.0 -38.0
        3         115  1044.782609     106.0 -45.0
        4         110  1111.572727     344.0 -35.0
        5         109  1110.385321     154.0 -38.0
        6         103  1049.067961     297.0 -57.0
        7         107  1036.738318     264.0 -45.0
B6      1          70  1703.428571     184.0 -36.0
        2          79  1754.924051     164.0 -29.0
        3          78  1619.230769     331.0 -38.0
        4          84  1878.000000     239.0 -45.0
        5          84  1766.511905     123.0 -43.0
        6          60  1858.666667     131.0 -51.0
        7          88  1821.522727     171.0 -30.0
DL      1        1648   864.771238     692.0 -53.0
        2        1536   853.326823     573.0 -57.0
        3        1559   872.760103     264.0 -44.0
        4        1546   868.919793     293.0 -53.0
        5        1514   846.447820     529.0 -46.0
        6        1252   884.300319     741.0 -37.0
        7        1546   877.566624     334.0 -39.0
EV      1         879   449.378840     669.0 -38.0
        2         878   477.079727     295.0 -33.0
...               ...          ...       ...   ...
OO      6         829   536.881785     724.0 -39.0
        7         924   500.520563     290.0 -33.0
UA      1        1216  1205.710526     500.0 -48.0
        2        1143  1209.221347     682.0 -41.0
        3        1154  1225.072790    1185.0 -58.0
        4        1166  1214.204117     557.0 -42.0
        5        1177  1227.108751     260.0 -48.0
        6         898  1274.632517     341.0 -48.0
        7        1038  1276.120424     589.0 -47.0
US      1         223  1265.470852     196.0 -51.0
        2         222  1198.504505     170.0 -50.0
        3         220  1222.004545     172.0 -42.0
        4         253  1176.750988     239.0 -37.0
        5         221  1207.099548     431.0 -41.0
        6         213  1042.272300     172.0 -37.0
        7         263  1156.201521     125.0 -48.0
VX      1         139  1379.762590     236.0 -30.0
        2         130  1260.138462     164.0 -40.0
        3         183  1310.442623     156.0 -39.0
        4         141  1229.978723     230.0 -25.0
        5         150  1110.313333     207.0 -51.0
        6         115  1067.243478     189.0 -35.0
        7         135  1285.118519     208.0 -39.0
WN      1        1259   803.131056     493.0 -33.0
        2        1278   809.537559     248.0 -35.0
        3        1275   782.127843     262.0 -38.0
        4        1264   810.802215     284.0 -52.0
        5        1201   816.849292     244.0 -44.0
        6         987   834.798379     290.0 -41.0
        7        1154   819.479203     261.0 -45.0

[98 rows x 4 columns]

In [34]:
flights.reset_index()

,index,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0
2,2,1,1,4,MQ,DFW,VPS,1305,36.0,85.0,641,1453,35.0,0,0
3,3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
4,4,1,1,4,WN,LAX,MCI,1720,48.0,166.0,1363,2225,39.0,0,0
5,5,1,1,4,UA,IAH,SAN,1450,1.0,178.0,1303,1620,-14.0,0,0
6,6,1,1,4,AA,DFW,MSY,1250,84.0,64.0,447,1410,83.0,0,0
7,7,1,1,4,F9,SFO,PHX,1020,-7.0,91.0,651,1315,-6.0,0,0
8,8,1,1,4,AA,ORD,STL,1845,-5.0,44.0,258,1950,-5.0,0,0
9,9,1,1,4,UA,IAH,SJC,925,3.0,215.0,1608,1136,-14.0,0,0
10,10,1,1,4,MQ,DFW,DRO,1335,28.0,104.0,674,1438,28.0,0,0
11,11,1,1,4,EV,ORD,JAN,1155,6.0,113.0,677,1403,5.0,0,0
12,12,1,1,4,OO,ORD,MSP,1510,2.0,65.0,334,1646,4.0,0,0
13,13,1,1,4,EV,ORD,CMH,1010,-2.0,46.0,296,1228,-9.0,0,0
14,14,1,1,4,UA,IAH,IND,1426,-1.0,102.0,844,1742,-20.0,0,0
15,15,1,1,4,AA,DEN,DFW,1445,-6.0,93.0,641,1745,4.0,0,0
16,16,1,1,4,OO,DEN,SGU,1105,21.0,66.0,517,1249,20.0,0,0
17,17,1,1,4,NK,DEN,DTW,1952,37.0,124.0,1123,31,54.0,0,0
18,18,1,1,4,MQ,ORD,DAY,2220,19.0,37.0,240,23,20.0,0,0
19,19,1,1,4,WN,PHX,LAX,1640,51.0,58.0,370,1700,59.0,0,0
20,20,1,1,4,WN,ATL,BWI,1115,1.0,76.0,577,1305,-15.0,0,0
21,21,1,1,4,UA,ORD,CLE,2102,48.0,47.0,315,2320,41.0,0,0
22,22,1,1,4,OO,LAS,LAX,1544,-4.0,39.0,236,1655,-12.0,0,0
23,23,1,1,4,WN,ATL,HOU,1555,30.0,113.0,696,1720,18.0,0,0
24,24,1,1,4,MQ,DFW,BTR,730,NaN,NaN,383,853,NaN,0,1
25,25,1,1,4,OO,ORD,SPI,2110,-4.0,31.0,174,2205,5.0,0,0
26,26,1,1,4,AA,LAX,AUS,1430,33.0,157.0,1242,1925,41.0,0,0
27,27,1,1,4,OO,IAH,JAC,1104,-1.0,161.0,1265,1316,-1.0,0,0
28,28,1,1,4,WN,ATL,MDW,935,1.0,97.0,591,1035,-4.0,0,0
29,29,1,1,4,EV,ORD,IND,1025,-6.0,29.0,177,1228,-19.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58462,58462,12,31,4,AA,DFW,PBI,1355,0.0,130.0,1102,1732,-2.0,0,0
58463,58463,12,31,4,EV,ORD,MSN,1220,18.0,32.0,108,1319,27.0,0,0
58464,58464,12,31,4,DL,LAX,SFO,700,108.0,54.0,337,825,105.0,0,0
58465,58465,12,31,4,AA,ORD,PHL,1655,28.0,80.0,678,1957,2.0,0,0
58466,58466,12,31,4,AA,PHX,ORD,820,19.0,156.0,1440,1250,-5.0,0,0
58467,58467,12,31,4,DL,ATL,IND,1235,-3.0,63.0,432,1407,-13.0,0,0
58468,58468,12,31,4,MQ,DFW,OKC,1720,-3.0,31.0,175,1819,-10.0,0,0
58469,58469,12,31,4,NK,LAS,MSY,1950,124.0,163.0,1500,112,101.0,0,0
58470,58470,12,31,4,AA,DFW,FAT,1020,-3.0,196.0,1313,1156,-2.0,0,0
58471,58471,12,31,4,VX,SFO,LAX,700,6.0,51.0,337,820,3.0,0,0
58472,58472,12,31,4,WN,PHX,HOU,845,5.0,119.0,1020,1210,7.0,0,0
58473,58473,12,31,4,WN,DEN,PDX,1205,4.0,130.0,991,1400,-13.0,0,0
58474,58474,12,31,4,MQ,ORD,FNT,829,4.0,40.0,223,1034,-4.0,0,0
58475,58475,12,31,4,AA,IAH,CLT,710,1.0,113.0,912,1037,-12.0,0,0
58476,58476,12,31,4,AA,DFW,TPA,1020,-3.0,121.0,929,1340,-6.0,0,0
58477,58477,12,31,4,B6,DFW,BOS,1145,12.0,161.0,1562,1608,-14.0,0,0
58478,58478,12,31,4,VX,SFO,LAX,1530,29.0,52.0,337,1650,22.0,0,0
58479,58479,12,31,4,AA,DFW,ELP,1200,3.0,94.0,551,1250,13.0,0,0
58480,58480,12,31,4,OO,MSP,BIS,1310,-2.0,65.0,386,1449,-9.0,0,0
58481,58481,12,31,4,UA,IAH,LAX,1433,1.0,197.0,1379,1625,-13.0,0,0
58482,58482,12,31,4,OO,DEN,CPR,1850,-2.0,38.0,230,1956,1.0,0,0
58483,58483,12,31,4,B6,PHX,BOS,2236,-12.0,231.0,2300,515,-45.0,0,0
58484,58484,12,31,4,MQ,ORD,DSM,1333,1.0,57.0,299,1455,-7.0,0,0
58485,58485,12,31,4,DL,ATL,CMH,2206,2.0,64.0,447,2338,-8.0,0,0
58486,58486,12,31,4,EV,DFW,LFT,850,21.0,52.0,351,1012,14.0,0,0
58487,58487,12,31,4,AA,SFO,DFW,515,5.0,166.0,1464,1045,-19.0,0,0
58488,58488,12,31,4,F9,LAS,SFO,1910,13.0,71.0,414,2050,4.0,0,0
58489,58489,12,31,4,OO,SFO,SBA,1846,-6.0,46.0,262,1956,-5.0,0,0
58490,58490,12,31,4,WN,MSP,ATL,525,39.0,124.0,907,855,34.0,0,0
58491,58491,12,31,4,OO,SFO,BOI,859,5.0,73.0,522,1146,-1.0,0,0

In [35]:
# Writing customized functions in Pandas for group by

![title](1.png)

In [39]:
college= pd.read_csv("college.csv")
college

,INSTNM,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
0,Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
1,University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
2,Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
3,University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
4,Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5
5,The University of Alabama,Tuscaloosa,AL,0.0,0.0,0.0,0,555.0,565.0,0.0,...,0.0261,0.0268,0.0026,0.0844,1,0.2040,0.4010,0.0853,41900,23750
6,Central Alabama Community College,Alexander City,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0000,0.0000,0.0019,0.3882,1,0.5892,0.3977,0.3153,27500,16127
7,Athens State University,Athens,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0174,0.0057,0.0334,0.5517,1,0.4088,0.6296,0.6410,39000,18595
8,Auburn University at Montgomery,Montgomery,AL,0.0,0.0,0.0,0,486.0,509.0,0.0,...,0.0297,0.0397,0.0246,0.2853,1,0.4192,0.5803,0.2930,35000,21335
9,Auburn University,Auburn,AL,0.0,0.0,0.0,0,575.0,588.0,0.0,...,0.0000,0.0100,0.0140,0.0862,1,0.1610,0.3494,0.0415,45700,21831
10,Birmingham Southern College,Birmingham,AL,0.0,0.0,0.0,1,560.0,560.0,0.0,...,0.0051,0.0000,0.0051,0.0017,1,0.1920,0.4809,0.0152,44200,27000
11,Chattahoochee Valley Community College,Phenix City,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0151,0.0000,0.0139,0.4198,1,0.6369,0.2537,0.3876,26100,9000
12,Concordia College Alabama,Selma,AL,1.0,0.0,0.0,1,420.0,400.0,0.0,...,0.0031,0.0466,0.0000,0.1056,1,0.8667,0.9333,0.2367,19900,PrivacySuppressed
13,South University-Montgomery,Montgomery,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0000,0.0019,0.0326,0.3238,1,0.6845,0.7129,0.5726,28800,25167
14,Enterprise State Community College,Enterprise,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0254,0.0012,0.0069,0.3823,1,0.4895,0.2263,0.3399,24600,8273
15,James H Faulkner State Community College,Bay Minette,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0152,0.0007,0.0009,0.4104,1,0.4725,0.3741,0.2909,28700,11000
16,Faulkner University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,0.0,...,0.0173,0.0182,0.0258,0.2302,1,0.5812,0.7253,0.4589,37200,22000
17,Gadsden State Community College,Gadsden,AL,1.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0185,0.0150,0.0169,0.4523,1,0.5734,0.0000,0.3733,25700,PrivacySuppressed
18,New Beginning College of Cosmetology,Albertville,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0000,0.0000,0.0000,0.0783,1,0.8224,0.8553,0.3933,NaN,5500
19,George C Wallace State Community College-Dothan,Dothan,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0126,0.0000,0.0009,0.4787,1,0.5501,0.0000,0.3920,26600,PrivacySuppressed
20,George C Wallace State Community College-Hance...,Hanceville,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0000,0.0059,0.0183,0.4203,1,0.5026,0.4192,0.3229,28800,11186
21,George C Wallace State Community College-Selma,Selma,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0033,0.0040,0.0443,0.3840,1,0.7645,0.0000,0.3318,24200,PrivacySuppressed
22,Herzing University-Birmingham,Birmingham,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0563,0.0000,0.0397,0.5497,1,0.6541,0.7736,0.7813,42300,23216.5
23,Huntingdon College,Montgomery,AL,0.0,0.0,0.0,1,510.0,490.0,0.0,...,0.0261,0.0061,0.0827,0.2097,1,0.3982,0.7153,0.1937,36500,26230
24,Heritage Christian University,Florence,AL,0.0,0.0,0.0,1,NaN,NaN,0.0,...,0.0000,0.0161,0.0323,0.4355,1,0.6087,0.4493,0.5942,PrivacySuppressed,PrivacySuppressed
25,J F Drake State Community and Technical College,Huntsville,AL,1.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0185,0.0000,0.0062,0.4394,1,0.5763,0.0000,0.4555,22300,PrivacySuppressed
26,Jacksonville State University,Jacksonville,AL,0.0,0.0,0.0,0,495.0,485.0,0.0,...,0.0000,0.0234,0.0280,0.1989,1,0.4428,0.6825,0.2200,34600,23000
27,Jefferson Davis Community College,Brewton,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0184,0.0000,0.0397,0.4424,1,0.5765,0.0000,0.4060,25400,PrivacySuppressed
28,Jefferson State Community College,Birmingham,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0301,0.0054,0.0001,0.6050,1,0.3372,0.2101,0.3671,29400,8916.5
29,John C Calhoun State Community College,Tanner,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0428,0.0062,0.0162,0.5795,1,0.3933,0.3024,0.3688,27400,10500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7505,Strayer University-Lawrenceville,Lawrenceville,NJ,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7506,Strayer University-Piscataway,Piscataway,NJ,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7507,Utah County Campus,Orem,UT,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,7667
7508,L'esprit Academy - Royal Oak,Royal Oak,MI,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,9833
7509,National Career Institute - Jersey City Branch,Jersey City,NJ,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,9500
7510,Strayer University-Cobb Campus,Atlanta,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7511,Strayer University-Morrow Campus,Morrow,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7512,Strayer University-Roswell Campus,Roswell,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7513,Strayer University-Douglasville Campus,Douglasville,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7514,Strayer University-Lithonia Campus,Lithonia,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7515,Strayer University-Savannah Campus,Savannah,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7516,Strayer University-Augusta Campus,Augusta,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7517,Strayer University-Columbus,Columbus,GA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,49200,36173.5
7518,Strayer University-Columbia Campus,Columbia,SC,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7519,Strayer University-Charleston Campus,North Charleston,SC,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7520,Strayer University-Irving,Irving,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7521,Strayer University-Katy,Houston,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7522,Strayer University-Northwest Houston,Houston,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7523,Strayer University-Plano,Plano,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,49200,36173.5
7524,Strayer University-Cedar Hill,Cedar Hill,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
7525,Strayer University-North Dallas,Dallas,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
7526,Strayer University-San Antonio,San Antonio,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
7527,Strayer University-Stafford,Stafford,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,36173.5
7528,WestMed College - Merced,Merced,CA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,15623.5
7529,Vantage College,El Paso,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,9500
7530,SAE Institute of Technology San Francisco,Emeryville,CA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,9500
7531,Rasmussen College - Overland Park,Overland Park,KS,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,21163
7532,National Personal Training Institute of Cleveland,Highland Heights,OH,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,6333
7533,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
7534,Excel Learning Center-San Antonio South,San Antonio,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,12125

In [43]:
college.groupby("STABBR")['UGDS'].agg(['mean','std']).head()

               mean           std
STABBR
AK      2493.200000   4051.726650
AL      2789.865169   4657.877043
AR      1644.146341   3142.774213
AS      1276.000000           NaN
AZ      4130.468254  14893.640651

![title](2.png)

In [49]:
def percentagebeteen(s,low,high):
    return s.between(low,high).mean()

In [55]:
college.groupby(["STABBR",'RELAFFIL'])['UGDS'].agg(percentagebeteen,low=1000,high=10000).head()

STABBR  RELAFFIL
AK      0           0.428571
        1           0.000000
AL      0           0.458333
        1           0.375000
AR      0           0.397059
Name: UGDS, dtype: float64

![title](3.png)

In [56]:
college.head(2)

,INSTNM,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
0,Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
1,University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5